# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install JDK 16
    init: cp /workspace/AdventOfCode/gitpod/sdkman-config /home/gitpod/.sdkman/etc/config && sdk install java 16.0.2.fx-zulu
    command: ./gradlew jar

github:
  prebuilds:
    master: false
    branches: false

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
